"use client";

import { BriefcaseBusiness, CalendarDays, Camera, ChevronRight, CircleDollarSign, FileText, Gauge, HardHat, Menu, Plus, ReceiptText, Save, Settings, Trash2, TrendingUp, Users, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Kind = "expenses" | "customers" | "jobs" | "income" | "mileage";
type View = "overview" | "receipts" | "calendar" | "jobs" | "money" | "reports" | "customers" | "settings";
type Row = Record<string, string | number | null> & { id: number };
type Totals = { expenses:number; income:number; miles:number; review:number; profit:number };
type CreateRecord = (kind:Kind, values:Record<string,FormDataEntryValue>, receiptKey?:string) => Promise<boolean>;
type RemoveRecord = (kind:Kind, id:number) => Promise<void>;

const kinds: Kind[] = ["expenses", "customers", "jobs", "income", "mileage"];
const nav: Array<{ id: View; label: string; icon: typeof Gauge }> = [
  { id: "overview", label: "Overview", icon: Gauge }, { id: "receipts", label: "Receipts", icon: ReceiptText },
  { id: "calendar", label: "Calendar", icon: CalendarDays }, { id: "jobs", label: "Jobs", icon: HardHat },
  { id: "money", label: "Money", icon: CircleDollarSign }, { id: "reports", label: "Reports", icon: FileText },
  { id: "customers", label: "Customers", icon: Users }, { id: "settings", label: "Settings", icon: Settings },
];
const categories = ["Materials", "Tools", "Vehicle", "Fuel", "Phone & internet", "Business meal", "Home office", "Insurance", "Licenses & permits", "Other"];
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export default function FieldLedger({ displayName }: { displayName: string }) {
  const [view, setView] = useState<View>("overview"); const [open, setOpen] = useState(false);
  const [rows, setRows] = useState<Record<Kind, Row[]>>({ expenses: [], customers: [], jobs: [], income: [], mileage: [] });
  const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const results = await Promise.all(kinds.map(async kind => { const response = await fetch(`/api/records?kind=${kind}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load your records"); return [kind, await response.json()] as const; })); setRows(Object.fromEntries(results) as Record<Kind, Row[]>); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load your records"); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const totals = useMemo(() => { const expenses = rows.expenses.reduce((s,r)=>s+Number(r.amount||0),0); const income=rows.income.reduce((s,r)=>s+Number(r.amount||0),0); const miles=rows.mileage.reduce((s,r)=>s+Number(r.miles||0),0); return { expenses, income, miles, review: rows.expenses.filter(r=>r.review_status!=="ready").length, profit:income-expenses }; }, [rows]);
  async function create(kind:Kind, values:Record<string,FormDataEntryValue>, receiptKey="") { setNotice("Saving…"); const response=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,...values,receipt_key:receiptKey})}); if(!response.ok){setNotice((await response.json()).error??"Save failed");return false;} setNotice("Saved");await load();return true; }
  async function remove(kind:Kind,id:number){if(!confirm("Delete this record?"))return;const response=await fetch(`/api/records?kind=${kind}&id=${id}`,{method:"DELETE"});if(response.ok){setNotice("Deleted");await load();}}
  function choose(next:View){setView(next);setOpen(false);setNotice("");}
  return <main className="app-shell"><aside className={open?"side open":"side"}><div className="brand"><span className="brand-mark"><BriefcaseBusiness size={21}/></span><div><strong>1099 Field Ledger</strong><small>Electrical business OS</small></div><button className="icon mobile-close" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div><nav aria-label="Main navigation">{nav.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>choose(item.id)}><item.icon size={19}/><span>{item.label}</span><ChevronRight size={16}/></button>)}</nav><div className="side-note"><strong>Tax-ready, not tax advice</strong><span>Keep originals and have a tax professional review uncertain deductions.</span></div></aside>
    <section className="workspace"><header className="topbar"><button className="icon menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><div><small>Good to see you</small><strong>{displayName}</strong></div><div className="save-state"><Save size={16}/>{notice||"Changes save automatically"}</div></header><div className="content">{view==="overview"&&<Overview totals={totals} rows={rows} loading={loading} onNavigate={choose}/>} {view==="receipts"&&<Receipts rows={rows.expenses} create={create} remove={remove}/>} {view==="calendar"&&<Calendar rows={rows.jobs}/>} {view==="jobs"&&<Jobs rows={rows.jobs} customers={rows.customers} create={create} remove={remove}/>} {view==="money"&&<Money income={rows.income} mileage={rows.mileage} create={create} remove={remove}/>} {view==="reports"&&<Reports totals={totals} expenses={rows.expenses}/>} {view==="customers"&&<Customers rows={rows.customers} create={create} remove={remove}/>} {view==="settings"&&<SettingsPanel/>}</div></section>{open&&<button className="backdrop" onClick={()=>setOpen(false)} aria-label="Close menu"/>}</main>;
}

function Overview({totals,rows,loading,onNavigate}:{totals:Totals;rows:Record<Kind,Row[]>;loading:boolean;onNavigate:(v:View)=>void}){return <><div className="page-head"><div><p className="eyebrow">This year</p><h1>Business overview</h1><p>What came in, what went out, and what still needs your attention.</p></div><button className="primary" onClick={()=>onNavigate("receipts")}><Camera size={18}/>Add receipt</button></div><section className="metric-grid"><Metric label="Income" value={money.format(totals.income)} tone="blue"/><Metric label="Expenses" value={money.format(totals.expenses)} tone="amber"/><Metric label="Net before tax" value={money.format(totals.profit)} tone={totals.profit<0?"red":"green"}/><Metric label="Business miles" value={totals.miles.toLocaleString()} tone="slate"/></section><section className="two-col"><div className="panel"><div className="panel-head"><div><p className="eyebrow">Attention</p><h2>Tax review queue</h2></div><span className="count">{totals.review}</span></div>{totals.review===0?<Empty text="Nothing needs review yet."/>:rows.expenses.filter(r=>r.review_status!=="ready").slice(0,5).map(r=><Item key={r.id} icon={ReceiptText} title={String(r.vendor)} meta={String(r.review_note||"Check business purpose")} value={money.format(Number(r.amount))}/>)}</div><div className="panel"><div className="panel-head"><div><p className="eyebrow">Current work</p><h2>Open jobs</h2></div><button className="text-button" onClick={()=>onNavigate("jobs")}>View all</button></div>{loading?<Empty text="Loading…"/>:rows.jobs.length===0?<Empty text="No jobs yet. Add your first job."/>:rows.jobs.slice(0,5).map(r=><Item key={r.id} icon={HardHat} title={String(r.name)} meta={`${r.phase||"Planning"} · ${r.status||"Open"}`} value={money.format(Number(r.quoted_amount||0))}/>)}</div></section><section className="quick-grid"><Quick icon={ReceiptText} title="Capture receipt" text="Save the original and business details." action={()=>onNavigate("receipts")}/><Quick icon={HardHat} title="Track a job" text="Rough-in, trim-out, labor and materials." action={()=>onNavigate("jobs")}/><Quick icon={TrendingUp} title="Record income" text="Keep payments tied to your records." action={()=>onNavigate("money")}/></section></>}

function Receipts({rows,create,remove}:{rows:Row[];create:CreateRecord;remove:RemoveRecord}){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();let key="";if(file){const up=new FormData();up.set("file",file);const response=await fetch("/api/receipts",{method:"POST",body:up});if(!response.ok)return;key=(await response.json()).key;}const ok=await create("expenses",Object.fromEntries(new FormData(e.currentTarget)),key);if(ok){e.currentTarget.reset();setPreview("");setFile(null);}}return <><PageHead title="Receipts & expenses" text="Photograph the original, then record why it was a business expense."/><section className="split"><form className="panel form" onSubmit={submit}><h2>New expense</h2><label className="upload"><input type="file" accept="image/*,application/pdf" capture="environment" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setPreview(f&&f.type.startsWith("image/")?URL.createObjectURL(f):"");}}/><Camera size={28}/><strong>{file?file.name:"Photograph or upload receipt"}</strong><span>JPG, PNG, WEBP or PDF · max 10 MB</span>{preview&&<img src={preview} alt="Receipt preview"/>}</label><Field label="Vendor" name="vendor" required/><div className="form-grid"><Field label="Amount" name="amount" type="number" step="0.01" min="0.01" required/><Field label="Date" name="transaction_date" type="date" required/></div><label>Category<select name="category" required><option value="">Choose</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Business purpose" name="business_purpose" placeholder="Example: material for Smith rough-in"/><label className="check"><input type="checkbox" name="is_business_meal" value="1"/>This was a business meal</label><button className="primary"><Plus size={18}/>Save expense</button></form><div className="panel"><div className="panel-head"><div><p className="eyebrow">Saved</p><h2>Expense history</h2></div><span className="count">{rows.length}</span></div>{rows.length===0?<Empty text="Your dashboard starts at zero. Add a receipt when ready."/>:rows.map(r=><Item key={r.id} icon={ReceiptText} title={String(r.vendor)} meta={`${r.category} · ${r.transaction_date}${r.business_purpose?` · ${r.business_purpose}`:""}`} value={money.format(Number(r.amount))} remove={()=>remove("expenses",r.id)}/>)}</div></section></>}

function Jobs({rows,customers,create,remove}:{rows:Row[];customers:Row[];create:CreateRecord;remove:RemoveRecord}){return <><PageHead title="Jobs" text="Track each electrical job from estimate through rough-in and trim-out."/><section className="split"><form className="panel form" onSubmit={submitter("jobs",create)}><h2>New job</h2><Field name="name" label="Job name or lot" required/><label>Customer<select name="customer_id"><option value="">No customer selected</option>{customers.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><div className="form-grid"><label>Phase<select name="phase"><option>Estimate</option><option>Rough-in</option><option>Trim-out</option><option>Complete</option></select></label><Field name="quoted_amount" label="Quoted amount" type="number" step="0.01" min="0"/></div><Field name="start_date" label="Start date" type="date"/><Field name="address" label="Job address"/><Field name="notes" label="Scope notes" placeholder="Lights, outlets, switches, circuits, crew…"/><button className="primary"><Plus size={18}/>Create job</button></form><div className="panel"><h2>Job board</h2>{rows.length===0?<Empty text="No jobs have been added."/>:rows.map(r=><Item key={r.id} icon={HardHat} title={String(r.name)} meta={`${r.phase} · ${r.address||"No address"}`} value={money.format(Number(r.quoted_amount||0))} remove={()=>remove("jobs",r.id)}/>)}</div></section></>}
function Money({income,mileage,create,remove}:{income:Row[];mileage:Row[];create:CreateRecord;remove:RemoveRecord}){return <><PageHead title="Money & mileage" text="Record payments received and business driving while the details are fresh."/><section className="two-col"><form className="panel form" onSubmit={submitter("income",create)}><h2>Record income</h2><Field name="payer" label="Paid by" required/><div className="form-grid"><Field name="amount" label="Amount" type="number" step="0.01" min="0.01" required/><Field name="received_date" label="Date received" type="date" required/></div><Field name="method" label="Payment method" placeholder="Check, cash, ACH…"/><Field name="notes" label="Notes"/><button className="primary"><Plus size={18}/>Save income</button>{income.slice(0,4).map(r=><Mini key={r.id} title={String(r.payer)} meta={String(r.received_date)} value={money.format(Number(r.amount))} onDelete={()=>remove("income",r.id)}/>)}</form><form className="panel form" onSubmit={submitter("mileage",create)}><h2>Log business mileage</h2><Field name="trip_date" label="Trip date" type="date" required/><div className="form-grid"><Field name="miles" label="Miles" type="number" step="0.1" min="0.1" required/><Field name="vehicle" label="Vehicle" placeholder="1993 Silverado"/></div><Field name="purpose" label="Business purpose" required placeholder="Supply run for Lot 12"/><button className="primary"><Plus size={18}/>Save mileage</button>{mileage.slice(0,4).map(r=><Mini key={r.id} title={`${r.miles} miles`} meta={String(r.purpose)} value={String(r.trip_date)} onDelete={()=>remove("mileage",r.id)}/>)}</form></section></>}
function Customers({rows,create,remove}:{rows:Row[];create:CreateRecord;remove:RemoveRecord}){return <><PageHead title="Customers" text="Keep contact and job information together."/><section className="split"><form className="panel form" onSubmit={submitter("customers",create)}><h2>New customer</h2><Field name="name" label="Customer name" required/><Field name="phone" label="Phone" type="tel"/><Field name="email" label="Email" type="email"/><Field name="address" label="Address"/><Field name="notes" label="Notes"/><button className="primary"><Plus size={18}/>Save customer</button></form><div className="panel"><h2>Customer list</h2>{rows.length===0?<Empty text="No customers saved yet."/>:rows.map(r=><Item key={r.id} icon={Users} title={String(r.name)} meta={String(r.phone||r.email||"No contact details")} remove={()=>remove("customers",r.id)}/>)}</div></section></>}
function Reports({totals,expenses}:{totals:Totals;expenses:Row[]}){const by=Object.entries(expenses.reduce((a:Record<string,number>,r)=>{const k=String(r.category||"Other");a[k]=(a[k]||0)+Number(r.amount||0);return a;},{})).sort((a,b)=>b[1]-a[1]);return <><PageHead title="Reports" text="A clean year-to-date view for planning and accountant review."/><section className="metric-grid"><Metric label="Gross income" value={money.format(totals.income)} tone="blue"/><Metric label="Recorded expenses" value={money.format(totals.expenses)} tone="amber"/><Metric label="Net before tax" value={money.format(totals.profit)} tone="green"/><Metric label="Needs review" value={String(totals.review)} tone="red"/></section><section className="panel"><h2>Expenses by category</h2>{by.length===0?<Empty text="Categories will appear after you add expenses."/>:by.map(([name,value])=><div className="report-line" key={name}><span>{name}</span><div><i style={{width:`${Math.max(4,(value/totals.expenses)*100)}%`}}/></div><strong>{money.format(value)}</strong></div>)}<p className="disclaimer">Estimates are for recordkeeping only. Deductibility depends on business purpose, documentation, and current tax law. Business meals are flagged for review rather than automatically treated as fully deductible.</p></section></>}
function Calendar({rows}:{rows:Row[]}){return <><PageHead title="Calendar" text="A simple schedule view of jobs and phases."/><section className="panel"><h2>Upcoming work</h2>{rows.length===0?<Empty text="Jobs with scheduled dates will appear here."/>:rows.map(r=><Item key={r.id} icon={CalendarDays} title={String(r.name)} meta={`${r.start_date||"Date TBD"} · ${r.phase} · ${r.address||"Address pending"}`}/>)}</section></>}
function SettingsPanel(){const[saved,setSaved]=useState(false);return <><PageHead title="Settings" text="Choose defaults for this device."/><form className="panel form settings-form" onSubmit={e=>{e.preventDefault();localStorage.setItem("field-ledger-preferences",JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))));setSaved(true);}}><h2>Business profile</h2><Field name="business_name" label="Business name" placeholder="S.S. Electric"/><Field name="tax_year" label="Tax year" type="number" defaultValue={new Date().getFullYear()}/><label>Default review<select name="review_default"><option value="review">Review before tax export</option><option value="ready">Mark documented expenses ready</option></select></label><button className="primary"><Save size={18}/>{saved?"Saved":"Save preferences"}</button><p className="disclaimer">Device preferences do not change tax treatment. Business records remain stored securely with the app.</p></form></>}

function submitter(kind:Kind,create:CreateRecord){return async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const ok=await create(kind,Object.fromEntries(new FormData(e.currentTarget)));if(ok)e.currentTarget.reset();}}
function Metric({label,value,tone}:{label:string;value:string;tone:string}){return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></div>}
function Quick({icon:Icon,title,text,action}:{icon:LucideIcon;title:string;text:string;action:()=>void}){return <button className="quick" onClick={action}><span><Icon size={21}/></span><div><strong>{title}</strong><small>{text}</small></div><ChevronRight size={18}/></button>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...input}=props;return <label>{label}<input {...input}/></label>}
function Empty({text}:{text:string}){return <div className="empty"><ReceiptText size={28}/><span>{text}</span></div>}
function PageHead({title,text}:{title:string;text:string}){return <div className="page-head"><div><p className="eyebrow">1099 workspace</p><h1>{title}</h1><p>{text}</p></div></div>}
function Item({icon:Icon,title,meta,value,remove}:{icon:LucideIcon;title:string;meta:string;value?:string;remove?:()=>void}){return <div className="row"><span className="row-icon"><Icon size={18}/></span><div><strong>{title}</strong><small>{meta}</small></div>{value&&<b>{value}</b>}{remove&&<button className="delete" onClick={remove} aria-label={`Delete ${title}`}><Trash2 size={17}/></button>}</div>}
function Mini({title,meta,value,onDelete}:{title:string;meta:string;value:string;onDelete:()=>void}){return <div className="mini"><div><strong>{title}</strong><small>{meta}</small></div><b>{value}</b><button type="button" className="delete" onClick={onDelete}><Trash2 size={15}/></button></div>}
